name: Metrics
on:
  # Roda a cada 6 horas
  schedule:
    - cron: "0 */6 * * *"
  # Permite rodar manualmente
  workflow_dispatch:

jobs:
  render_metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token de autenticação
          token: ${{ secrets.GITHUB_TOKEN }}
          
          # Nome de usuário do GitHub
          user: DougGomesss
          
          # Arquivo de saída
          filename: metrics.isocalendar.svg
          
          # Plugins a serem usados
          # Habilita o plugin de calendário isométrico
          plugins: isocalendar
          
          # Opções do plugin isocalendar
          plugin_isocalendar_duration: full-year # Mostra o ano inteiro
