name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Garante que o diretório de saída exista
      - name: Create output directory
        run: mkdir -p dist

      # Gera a animação da Snake
      - uses: Platane/snk@v3
        with:
          github_user_name: DougGomesss
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica os arquivos gerados na branch 'output'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
