name: Generate Datas

on:
  schedule:
    # Executa a cada 12 horas (às 00:00 e 12:00 UTC)
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    # ↓↓ ESTA É A CORREÇÃO PRINCIPAL ↓↓
    permissions:
      contents: write 

    steps:
      # Gera a animação da Snake
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica os arquivos gerados na branch 'output'
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
